name: $(Date:yyyyMM).$(Rev:r)-$(SourceBranchName)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Renovate'

steps:
- bash: |
    git config --global user.email 'bot@renovateapp.com'
    git config --global user.name 'Renovate Bot'
    npx renovate
  env:
    TOKEN: $(System.AccessToken)
    RENOVATE_TOKEN: $(RENOVATE_TOKEN)
    GITHUB_COM_TOKEN: $(GITHUB_COM_TOKEN)
    RENOVATE_PASSWORD: $(RENOVATE_PASSWORD)
    LOG_LEVEL: debug
