name: Renovate
on:
  workflow_dispatch
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@af0eb69ad0365d53c161661d5c8a5ba5f12545d0 # v39.2.0
        with:
          configurationFile: config.js
          token: ${{ secrets.GITH_COM_TOKEN }}
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.GITH_COM_TOKEN }}
          RENOVATE_CLIENTID: ${{ secrets.RENOVATE_CLIENTID }}
          RENOVATE_PASSWORD: ${{ secrets.RENOVATE_PASSWORD }}
          LOG_LEVEL: debug
